name = "f2f-transfer"
compatibility_date = "2025-11-20"
pages_build_output_dir = "./public"

# KV 命名空间绑定
# 请使用 wrangler kv:namespace create "TRANSFERS" 创建你自己的 KV 命名空间
# 然后将生成的 ID 替换下面的示例值
[[kv_namespaces]]
binding = "TRANSFERS"
id = "7f23759dba224602a9e48fac2c8097cd"
preview_id = "de29319ba2c041dca61d21dee680edb0"
